import "./globals.css";
import Socials from "./components/layouts/Socials";
import Info from "./components/layouts/Info";
import Navbar from "./components/Navbar";

export const metadata = {
  title: "Pet Services",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Socials />
        <Info />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
